default:
  image: node:20.12
  before_script: npm install

stages:
  - lint
  - build
  - test

cache:
  # https://nextjs.org/docs/pages/building-your-application/deploying/ci-build-caching#gitlab-ci
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .next/cache/
    - ~/.cache/Cypress

lint:
  stage: lint
  script: npm run lint

check_style:
  stage: lint
  script: 'npm run format:check'

build:
  stage: build
  script: npm run build

test_unit:
  stage: test
  script: npm run test
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'

# The following jobs are currently broken

# test_component:
#   stage: test
#   image: cypress/included:13.8.1
#   script: 'npm run component:headless'

# test_e2e:
#   stage: test
#   image: cypress/included:13.8.1
#   script: 'npm run e2e:headless'
