default:
  image: node:20.12
  before_script: npm install

stages:
  - lint
  - build
  - test

cache:
  # https://nextjs.org/docs/pages/building-your-application/deploying/ci-build-caching#gitlab-ci
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .next/cache/

# lint:
#   stage: lint
#   script: npm run lint

# build:
#   stage: build
#   script: npm run build

# test_unit:
#   stage: test
#   script: npm run test
  # TODO coverage

# TODO e2e
test_component:
  stage: test
  image: cypress/included:cypress-13.8.1-node-20.12.2-chrome-124.0.6367.60-1-ff-125.0.2-edge-124.0.2478.51-1
  script: 'npm run component:headless'