services:
  dev:
    container_name: alexandria_frontend
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    env_file:
      - .env.docker
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
    networks:
      - alexandria_network

# TODO production

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  alexandria_network:
    # name must be specified to ensure it's the same in both frontend an backend
    name: alexandria_network 
    # tells compose to use the network created by the backend
    external: true 

